name: test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # installs your project and its deps
          pip install pydantic  # explicit in case it's missing

      - name: Run tuned-cap test
        run: python -m scripts.test_tuned_cap
