name: Schema check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install jsonschema
        run: |
          python -m pip install --upgrade pip jsonschema

      - name: Validate golden vectors
        run: |
          set -e
          echo "Validating receipt-min.json against receipt.schema.json"
          python -m jsonschema -i schemas/vectors/receipt-min.json schemas/receipt.schema.json
          echo "Validating frame-min.json against frame.schema.json"
          python -m jsonschema -i schemas/vectors/frame-min.json   schemas/frame.schema.json
          echo "Golden vectors OK."

      - name: Validate repo receipt if present
        run: |
          set -e
          if [ -f docs/receipt.latest.json ]; then
            echo "Validating docs/receipt.latest.json"
            python -m jsonschema -i docs/receipt.latest.json schemas/receipt.schema.json
            echo "docs/receipt.latest.json OK."
          else
            echo "No docs/receipt.latest.json; skipping."
          fi
